import type { NativeParityMatrixRowType, NativeParityMatrixSummaryType } from "./parity-matrix.js"

const HOST_PROTOCOL_METHOD_PATTERN =
  /pub const ([A-Z0-9_]+_(?:METHOD|EVENT)): &str\s*=\s*"([^"]+)";/gu
const HOST_ROUTER_METHOD_PATTERN = /host_protocol::([A-Z0-9_]+_METHOD)(?:\s*=>|\b)/gu

interface NativeParityMatrixDocument {
  readonly rows: readonly NativeParityMatrixRowType[]
  readonly summary: NativeParityMatrixSummaryType
}

export const routedHostMethodsFromSource = (
  protocolSource: string,
  routerSource: string
): ReadonlySet<string> => {
  const protocolMethods = new Map<string, string>()
  for (const match of protocolSource.matchAll(HOST_PROTOCOL_METHOD_PATTERN)) {
    const [, constantName, method] = match
    if (constantName !== undefined && method !== undefined) {
      protocolMethods.set(constantName, method)
    }
  }

  const dispatchSource = hostDispatchSource(routerSource)
  const routedMethods = new Set<string>()
  for (const match of dispatchSource.matchAll(HOST_ROUTER_METHOD_PATTERN)) {
    const [, constantName] = match
    if (constantName === undefined) {
      continue
    }
    const method = protocolMethods.get(constantName)
    if (method !== undefined) {
      routedMethods.add(method)
    }
  }

  const windowEventMethod = protocolMethods.get("WINDOW_EVENT")
  if (windowEventMethod !== undefined && routerSource.includes("install_window_event_sender")) {
    routedMethods.add(windowEventMethod)
  }

  return Object.freeze(routedMethods)
}

export const formatNativeParityMatrixMarkdown = (matrix: NativeParityMatrixDocument): string => {
  const tableRows = [
    ["Surface", "Method", "Support", "Host method", "Host router", "Release"],
    ...matrix.rows.map((row) => [
      `\`${row.surface}\``,
      `\`${row.method}\``,
      `\`${row.support.status}\``,
      `\`${row.hostMethod ?? row.tag}\``,
      `\`${row.hostStatus}\``,
      releaseCell(row.release)
    ])
  ]
  const widths =
    tableRows[0]?.map((_, column) =>
      Math.max(...tableRows.map((row) => row[column]?.length ?? 0))
    ) ?? []
  const lines = [
    "---",
    "title: Native parity matrix",
    "description: Generated TypeScript native surface to Rust host dispatch registry parity.",
    "kind: reference",
    "audience: maintainers",
    "effect_version: 4",
    "---",
    "",
    "# Native parity matrix",
    "",
    "This page is generated by `bun scripts/generate-native-parity-matrix.ts` from `Native.all` schema docs and the Rust host dispatch registry.",
    "",
    `- Total declared native methods: ${matrix.summary.total}`,
    `- Routed by the Rust host: ${matrix.summary.routed}`,
    `- Missing from the Rust host dispatch registry: ${matrix.summary.missing}`,
    `- Release-complete rows: ${matrix.summary.releaseComplete}`,
    `- Rows tracked by release issues: ${matrix.summary.releaseTracked}`,
    `- Rows missing release tracking: ${matrix.summary.releaseUntracked}`,
    "",
    "The machine-readable matrix lives in [`parity-matrix.json`](parity-matrix.json).",
    "",
    tableLine(tableRows[0] ?? [], widths),
    tableLine(
      widths.map((width) => "-".repeat(width)),
      widths
    )
  ]

  for (const row of tableRows.slice(1)) {
    lines.push(tableLine(row, widths))
  }

  lines.push("")
  return lines.join("\n")
}

const hostDispatchSource = (routerSource: string): string => {
  const start = routerSource.indexOf("const HOST_DISPATCH_ROUTES:")
  if (start === -1) {
    throw new Error("host dispatch registry not found")
  }
  const end = routerSource.indexOf("const fn route(", start)
  if (end === -1) {
    throw new Error("host dispatch registry end not found")
  }
  return routerSource.slice(start, end)
}

const tableLine = (row: readonly string[], widths: readonly number[]): string =>
  `| ${row.map((cell, index) => cell.padEnd(widths[index] ?? cell.length)).join(" | ")} |`

const releaseCell = (release: NativeParityMatrixRowType["release"]): string => {
  if (release.status === "complete") {
    return "`complete`"
  }
  if (release.status === "tracked") {
    return `[#${release.issue}](${release.url})`
  }
  return "`untracked`"
}
